### PR TITLE
Change 172.42 to 172.16

### PR DESCRIPTION
**Pull request by kinneyd81**
The 172.42.x.x block of ip's are reserved for use on the internet. This pull request changes them to 172.16.x.x which are private ip's that should be used on local networks.

### CODE REVIEW

**Comment by justmeandopensource** [comment]
Thanks for this update. I would like to keep the IP addresses easy to remember. Could you please update it to **172.16.16**? Thanks

**Comment by kinneyd81** [comment]
Sure thing. Thanks for looking at the PR. Love the channel keep up the good work.

**Comment by justmeandopensource** [comment]
Thanks for these changes

**Comment by justmeandopensource** [comment]
Closes #35

**Pull request merged**
